import './../globals.scss';
import { Inter } from 'next/font/google';
import Link from 'next/link';
import { getDictionary } from '@/dictionaries';

const inter = Inter({ subsets: ['latin'] });

// Components
import LocaleSwitcher from '@/components/LocaleSwitcher';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children, params: { lang } }) {
  const dict = await getDictionary(lang);
  return (
    <html lang={lang}>
      <body className={inter.className}>
        {/* Heading */}
        <LocaleSwitcher dict={dict} />
        <main>{children}</main>
        <Link href='/'>Home</Link>
        <Link href='/about'>Move</Link>
        {/* Fotter */}
      </body>
    </html>
  );
}
