import './../globals.scss';
import { Inter } from 'next/font/google';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children, params: { lang } }) {
  return (
    <html lang={lang}>
      <body className={inter.className}>
        {/* Heading */}
        <Link href={lang === 'es' ? '/en' : '/es'}>
          {lang === 'es' ? 'EN' : 'ES'}
        </Link>
        <main>{children}</main>
        <Link href='/'>Home</Link>
        <Link href='/about'>Move</Link>
        {/* Fotter */}
      </body>
    </html>
  );
}
