import './../globals.scss';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

// Components
import NavBar from '@/components/NavBar';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children, params: { locale = 'es' } }) {
  return (
    <html lang={locale}>
      <body className={inter.className}>
        {/* Heading */}
        <NavBar />
        <main>{children}</main>
        {/* Fotter */}
      </body>
    </html>
  );
}
