import './../globals.scss';
import { Inter } from 'next/font/google';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

// Components
import LocaleSwitcher from '@/components/LocaleSwitcher';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children, params: { locale = 'es' } }) {
  return (
    <html lang={locale}>
      <body className={inter.className}>
        {/* Heading */}
        <LocaleSwitcher />
        <main>{children}</main>
        <Link href='/'>Home</Link>
        <Link href='/about'>Move</Link>
        {/* Fotter */}
      </body>
    </html>
  );
}
